# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.SourceBranchName)-1.0$(Rev:.r)

trigger:
  batch: false
  branches:
    include:
      - master

variables:
  - name: GitVersion.SemVer
    value: ''
  - name: repositoryName
    value: repositoryNameXYZ
    
pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      if [ "$(Build.SourceBranchName)" == "master" ]; then
        echo "Versioning for master build"
        version=$(echo "$(Build.BuildNumber)" | cut -d "-" -f 2)
        echo "##vso[task.setvariable variable=version]$version"
        echo "##vso[task.setvariable variable=imageName]$(repositoryName):$version"
      elif [ -n "$(System.PullRequest.PullRequestId)" ]; then
        echo "Versioning for PR build"
        version=0.$(System.PullRequest.PullRequestId).$(build.buildId)
        echo "##vso[task.setvariable variable=version]$version"
        echo "##vso[task.setvariable variable=imageName]$(repositoryName):$version-pr"
      else
        echo "Branch is not for master nor a pull request"
        exit 1
      fi
    displayName: 'Set version and imageName variables'
    
  - bash: |
      echo "docker build --build-arg version=$(version) -t $(imageName) package"

