# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      ls -la /home/vsts/work/1/s

  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'
      includePrerelease: true
      useConfigFile: true
      configFilePath: '$(Build.SourcesDirectory)/GitVersion.yml'

  - task: gitreleasemanager/publish@0
    inputs:
      owner: 'antonios.klimis@gmail.com'
      repository: 'GitVersion101'
      token: 'a76d46aadce152c35db52ba48679b07fe6ac5e5f'
      tagName: $(gitversion.semver)
      targetDirectory: '$(Build.SourcesDirectory)'

