jobs:
  - job: Package
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      repositoryName: 'repositoryNameXYZ'
      version: '$(build.buildNumber)'
      imageName: '$(repositoryName):$(version)'
    steps:
      - bash: |
          echo "docker build --build-arg version=$(version) -t $(imageName) package"