# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

variables:
  - name: GitVersion.SemVer
    value: ''
    
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'
      includePrerelease: true
      useConfigFile: true
      configFilePath: '$(Build.SourcesDirectory)/GitVersion.yml'

  - bash: |
      echo "SemVer: $(GitVersion.SemVer)"
      
  - task: gitreleasemanager/create@0
    displayName: Create release with GitReleaseManager
    inputs:
      token: 'a76d46aadce152c35db52ba48679b07fe6ac5e5f'
      owner: 'klimisa'
      repository: 'GitVersion101'
      name: '$(GitVersion.SemVer)'
      assets: |
        GitVersion101.Api/Controllers/WeatherForecastController.cs
          
  # - task: gitreleasemanager/publish@0
  #   inputs:
  #     owner: 'klimisa'
  #     repository: 'GitVersion101'
  #     token: 'a76d46aadce152c35db52ba48679b07fe6ac5e5f'
  #     tagName: '$(GitVersion.SemVer)'

