name: pr-$(System.PullRequest.PullRequestNumber)$(Rev:.r)

trigger: none

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

jobs:
  - template: .devops/azure-pipelines-common.yml