# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: Package
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      repositoryName: 'repositoryNameXYZ'
      version: '$(build.buildNumber)'
      imageName: '$(repositoryName):$(version)'
    steps:
      - bash: |
          echo "docker build --build-arg version=$(version) -t $(imageName) package"

